# Generated by Django 5.1.1 on 2024-10-12 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("unit", models.CharField(max_length=10)),
                ("unit_price", models.FloatField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("labor_hours", models.FloatField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="TaskMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_tasks",
                        to="api.material",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_materials",
                        to="api.task",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="task",
            name="materials",
            field=models.ManyToManyField(through="api.TaskMaterial", to="api.material"),
        ),
    ]
