# Generated by Django 5.1.1 on 2024-10-12 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_material_task_taskmaterial_task_materials"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("labor_hours", models.FloatField()),
                ("description", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="ProjectMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_projects",
                        to="api.material",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_materials",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="materials",
            field=models.ManyToManyField(
                through="api.ProjectMaterial", to="api.material"
            ),
        ),
        migrations.CreateModel(
            name="ProjectTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.FloatField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_tasks",
                        to="api.project",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_projects",
                        to="api.task",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="project",
            name="tasks",
            field=models.ManyToManyField(through="api.ProjectTask", to="api.task"),
        ),
    ]
