# Generated by Django 5.1.1 on 2024-10-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_project_projectmaterial_project_materials_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="material",
            name="unit",
            field=models.CharField(max_length=20),
        ),
    ]
