# Generated by Django 5.1.1 on 2024-10-14 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_rename_labor_hours_project_contingency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="contingency",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="project",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects_coordinating",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
