# Generated by Django 5.1.1 on 2024-10-20 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_alter_employee_user_client_clientprofile_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="user",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Employee",
        ),
    ]
