# Generated by Django 5.1.1 on 2024-10-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_rename_ratings_employeetaskrating_rating"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="employeetaskrating",
            unique_together=set(),
        ),
    ]
