# Generated by Django 5.1.1 on 2024-10-23 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_employeetaskrating_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeetaskrating",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="api.employeeprofile",
            ),
        ),
        migrations.AlterField(
            model_name="employeetaskrating",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ratings",
                to="api.task",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="employeetaskrating",
            unique_together={("employee", "task")},
        ),
    ]
